[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "prague"
optimizer = true
optimizer_runs = 10000
bytecode_hash = "none"
cbor_metadata = false

[invariant]
runs = 64
depth = 32
fail_on_revert = false

[fmt]
line_length = 110
